#!/bin/bash
# Places the window to the right screen:
# [   ][x]
wmctrl -r :ACTIVE: -b remove,fullscreen
wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
wmctrl -r :ACTIVE: -e 0,3840,0,1920,1050
wmctrl -r :ACTIVE: -b add,maximized_vert
